-- AlterTable
ALTER TABLE "editeurs" ADD COLUMN     "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "workflow_status" "WorkflowStatus" NOT NULL DEFAULT 'PAS_DE_CONTACT';
